version: '3.8'
networks:
    app-network:
      driver: bridge
services:
  nodejs:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: 'unless-stopped'
    env_file: .env
    environment:
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASS=$MONGODB_PASS
    ports:
      - "80:8080"
    volumes:
      - .:/home/app
    networks:
      - app-network
  mongodb:
    image: 'bitnami/mongodb:latest'
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - './dbdata:/bitnami/mongodb'
    environment:
      - MONGODB_DATABASE=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASS
      - MONGODB_ROOT_PASSWORD=$MONGODB_PASS
    networks:
      - app-network

